services:
  backend:
    container_name: backend
    build: 
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - models:~/.cache/huggingface
    restart: unless-stopped
