services:
  backend:
    container_name: backend
    build: 
      context: .
    ports:
      - 80:8000
    env_file:
      - .env
    volumes:
      - models:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  models:
    external: true